name: Build and Publish Content On Every master update
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    name: Build and Publish content
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2
        with:
          path: './'
      - name: Detect yarn cache location
        id: yarn_cache
        shell: bash
        run: |
          yarn_cache_dir=`yarn cache dir`
          echo "::set-output name=yarn_cache_dir::$yarn_cache_dir"
        outputs:
          yarn_cache_dir:
            description: 'yarn cache location'
      - name: Set up workflow caching for yarn cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn_cache.outputs.yarn_cache_dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: yarn
      - name: Build content
        shell: bash
        run: yarn run build
      - name: Setup git creds
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local user.password ${{ secrets.GITHUB_TOKEN }}
      - name: Push content to gh-pages
        run: yarn run deploy
